---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Важно, чтобы интерфейс магазина был интуитивно понятным для пользователя, в т.ч. легкость навигации, интуитивное оформление заказа и понятные процессы оплаты
  - Информативное и точное описание товаров, высококачественные изображения, а также наличие отзывов и рейтингов товаров
  - Наличие информации о контактах для связи с поддержкой, а также удобные способы обратной связи для пользователей
  - Подробное описание условий возврата и обмена товара
  - Описание условий доставки товаров
  - Описание всех возможных условий оптаы товара
